services:
  web:
    container_name: challenge-web
    image: challenge-v3-frontend:dev
    env_file:
      - ./frontend/.env.dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
  api:
    container_name: challenge-api
    image: challenge-v3-backend:dev
    env_file:
      - ./backend/.env.dev
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    container_name: challenge-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./backend/.env.dev
    environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASS}
       POSTGRES_DB: ${DB_NAME}
    ports:
      - 5000:5432
    volumes:
      - industry-manager-db:/var/lib/postgresql/data

volumes:
  industry-manager-db:
          