services:
  web:
    container_name: web
    image: challenge-v3-frontend:dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
